// Code generated by goctl. DO NOT EDIT.
package types

type Application struct {
	ApplicationId string `json:"application_id"`
	Name          string `json:"name"`
	Avatar        string `json:"avatar"`
	ContactType   uint   `json:"contact_type"`
	Status        uint   `json:"status"`
	Notice        string `json:"notice"`
}

type Contact struct {
	ContactId      string `json:"contact_id"`
	ContactType    int64  `json:"contact_type"`
	Avatar         string `json:"avatar"`
	NoteName       string `json:"note_name"`
	LastMsgId      int64  `json:"last_msg_id"`
	LastMsgContent string `json:"last_msg_content"`
	LastMsgTime    string `json:"last_msg_time"`
}

type CreateContactApplicationReq struct {
	Uid         string `json:"uid"`
	ContactType uint   `json:"contact_type"`
	Notice      string `json:"notice"`
}

type CreateContactApplicationResp struct {
	ApplicationId string `json:"application_id"`
}

type CreateGroupReq struct {
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
	Notice string `json:"notice"`
}

type CreateGroupResp struct {
	Gid string `json:"gid"`
}

type DeleteContactReq struct {
	Uid string `json:"uid"`
}

type DeleteContactResp struct {
}

type DeleteGroupReq struct {
	Gid string `json:"gid"`
}

type DeleteGroupResp struct {
}

type DeleteUserGroupMapReq struct {
	Gid string `json:"gid"`
	Uid string `json:"uid"`
}

type DeleteUserGroupMapResp struct {
}

type GetContactApplicationListReq struct {
	ContactType int64 `json:"contact_type"`
	Page        int64 `json:"page"`
	Size        int64 `json:"size"`
}

type GetContactApplicationListResp struct {
	ApplicationList []Application `json:"application_list"`
	Total           int64         `json:"total"`
}

type GetContactListReq struct {
	NameOrUid string `json:"name_or_uid"`
	Page      int64  `json:"page"`
	Size      int64  `json:"size"`
}

type GetContactListResp struct {
	ContactList []Contact `json:"contact_list"`
	Total       int64     `json:"total"`
}

type GetListReq struct {
	Uid  string `json:"uid"`
	Page int64  `json:"page"`
	Size int64  `json:"size"`
}

type GetListResp struct {
	UserList []User `json:"user_list"`
	Total    int64  `json:"total"`
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegisterReq struct {
	Name     string `json:"name"`
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Mobile string `json:"mobile"`
}

type UpdateContactApplicationReq struct {
	ApplicationId string `json:"application_id"`
	Status        uint   `json:"status"`
}

type UpdateContactApplicationResp struct {
}

type UpdateGroupReq struct {
	Gid      string `json:"gid"`
	Name     string `json:"name"`
	Avatar   string `json:"avatar"`
	Notice   string `json:"notice"`
	AdminUid string `json:"admin_uid"`
}

type UpdateGroupResp struct {
}

type UpdateReq struct {
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
}

type UpdateResp struct {
	UserInfo User `json:"userInfo"`
}

type User struct {
	Uid    string `json:"uid"`
	Mobile string `json:"mobile"`
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
}
