// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.3
// source: apps/user/rpc/user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    string `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Mobile string `protobuf:"bytes,2,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Avatar string `protobuf:"bytes,4,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *User) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type Application struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicationId string `protobuf:"bytes,1,opt,name=ApplicationId,proto3" json:"ApplicationId,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Avatar        string `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	ContactType   int64  `protobuf:"varint,4,opt,name=ContactType,proto3" json:"ContactType,omitempty"`
	Status        int64  `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	Notice        string `protobuf:"bytes,6,opt,name=Notice,proto3" json:"Notice,omitempty"`
}

func (x *Application) Reset() {
	*x = Application{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{1}
}

func (x *Application) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *Application) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Application) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Application) GetContactType() int64 {
	if x != nil {
		return x.ContactType
	}
	return 0
}

func (x *Application) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Application) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

type Contact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContactId      string `protobuf:"bytes,1,opt,name=ContactId,proto3" json:"ContactId,omitempty"`
	ContactType    int64  `protobuf:"varint,2,opt,name=ContactType,proto3" json:"ContactType,omitempty"`
	Avatar         string `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	NoteName       string `protobuf:"bytes,4,opt,name=NoteName,proto3" json:"NoteName,omitempty"`
	LastMsgId      int64  `protobuf:"varint,5,opt,name=LastMsgId,proto3" json:"LastMsgId,omitempty"`
	LastMsgContent string `protobuf:"bytes,6,opt,name=LastMsgContent,proto3" json:"LastMsgContent,omitempty"`
	LastMsgTime    string `protobuf:"bytes,7,opt,name=LastMsgTime,proto3" json:"LastMsgTime,omitempty"`
}

func (x *Contact) Reset() {
	*x = Contact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{2}
}

func (x *Contact) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *Contact) GetContactType() int64 {
	if x != nil {
		return x.ContactType
	}
	return 0
}

func (x *Contact) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Contact) GetNoteName() string {
	if x != nil {
		return x.NoteName
	}
	return ""
}

func (x *Contact) GetLastMsgId() int64 {
	if x != nil {
		return x.LastMsgId
	}
	return 0
}

func (x *Contact) GetLastMsgContent() string {
	if x != nil {
		return x.LastMsgContent
	}
	return ""
}

func (x *Contact) GetLastMsgTime() string {
	if x != nil {
		return x.LastMsgTime
	}
	return ""
}

type LoginIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile   string `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *LoginIn) Reset() {
	*x = LoginIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginIn) ProtoMessage() {}

func (x *LoginIn) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginIn.ProtoReflect.Descriptor instead.
func (*LoginIn) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginIn) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *LoginIn) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken  string `protobuf:"bytes,1,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	AccessExpire int64  `protobuf:"varint,2,opt,name=AccessExpire,proto3" json:"AccessExpire,omitempty"`
	RefreshAfter int64  `protobuf:"varint,3,opt,name=RefreshAfter,proto3" json:"RefreshAfter,omitempty"`
}

func (x *LoginOut) Reset() {
	*x = LoginOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginOut) ProtoMessage() {}

func (x *LoginOut) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginOut.ProtoReflect.Descriptor instead.
func (*LoginOut) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginOut) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginOut) GetAccessExpire() int64 {
	if x != nil {
		return x.AccessExpire
	}
	return 0
}

func (x *LoginOut) GetRefreshAfter() int64 {
	if x != nil {
		return x.RefreshAfter
	}
	return 0
}

type RegisterIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Mobile   string `protobuf:"bytes,2,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *RegisterIn) Reset() {
	*x = RegisterIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterIn) ProtoMessage() {}

func (x *RegisterIn) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterIn.ProtoReflect.Descriptor instead.
func (*RegisterIn) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterIn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterIn) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterIn) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile string `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
}

func (x *RegisterOut) Reset() {
	*x = RegisterOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterOut) ProtoMessage() {}

func (x *RegisterOut) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterOut.ProtoReflect.Descriptor instead.
func (*RegisterOut) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterOut) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type GetListIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  string `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Page int64  `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	Size int64  `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
}

func (x *GetListIn) Reset() {
	*x = GetListIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListIn) ProtoMessage() {}

func (x *GetListIn) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListIn.ProtoReflect.Descriptor instead.
func (*GetListIn) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetListIn) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GetListIn) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListIn) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetListOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserList []*User `protobuf:"bytes,1,rep,name=UserList,proto3" json:"UserList,omitempty"`
	Total    int64   `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *GetListOut) Reset() {
	*x = GetListOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListOut) ProtoMessage() {}

func (x *GetListOut) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListOut.ProtoReflect.Descriptor instead.
func (*GetListOut) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetListOut) GetUserList() []*User {
	if x != nil {
		return x.UserList
	}
	return nil
}

func (x *GetListOut) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Avatar string `protobuf:"bytes,2,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
}

func (x *UpdateIn) Reset() {
	*x = UpdateIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIn) ProtoMessage() {}

func (x *UpdateIn) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIn.ProtoReflect.Descriptor instead.
func (*UpdateIn) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateIn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateIn) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UpdateOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateOut) Reset() {
	*x = UpdateOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOut) ProtoMessage() {}

func (x *UpdateOut) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOut.ProtoReflect.Descriptor instead.
func (*UpdateOut) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{10}
}

type CreateGroupIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Avatar string `protobuf:"bytes,2,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Notice string `protobuf:"bytes,3,opt,name=Notice,proto3" json:"Notice,omitempty"`
}

func (x *CreateGroupIn) Reset() {
	*x = CreateGroupIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupIn) ProtoMessage() {}

func (x *CreateGroupIn) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupIn.ProtoReflect.Descriptor instead.
func (*CreateGroupIn) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{11}
}

func (x *CreateGroupIn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupIn) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CreateGroupIn) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

type CreateGroupOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid string `protobuf:"bytes,1,opt,name=Gid,proto3" json:"Gid,omitempty"`
}

func (x *CreateGroupOut) Reset() {
	*x = CreateGroupOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGroupOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupOut) ProtoMessage() {}

func (x *CreateGroupOut) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupOut.ProtoReflect.Descriptor instead.
func (*CreateGroupOut) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{12}
}

func (x *CreateGroupOut) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

type UpdateGroupIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid      string `protobuf:"bytes,1,opt,name=Gid,proto3" json:"Gid,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Avatar   string `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Notice   string `protobuf:"bytes,4,opt,name=Notice,proto3" json:"Notice,omitempty"`
	AdminUid string `protobuf:"bytes,5,opt,name=AdminUid,proto3" json:"AdminUid,omitempty"`
}

func (x *UpdateGroupIn) Reset() {
	*x = UpdateGroupIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGroupIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupIn) ProtoMessage() {}

func (x *UpdateGroupIn) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupIn.ProtoReflect.Descriptor instead.
func (*UpdateGroupIn) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateGroupIn) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *UpdateGroupIn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupIn) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateGroupIn) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *UpdateGroupIn) GetAdminUid() string {
	if x != nil {
		return x.AdminUid
	}
	return ""
}

type UpdateGroupOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateGroupOut) Reset() {
	*x = UpdateGroupOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateGroupOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupOut) ProtoMessage() {}

func (x *UpdateGroupOut) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupOut.ProtoReflect.Descriptor instead.
func (*UpdateGroupOut) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{14}
}

type DeleteUserGroupMapIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid string `protobuf:"bytes,1,opt,name=Gid,proto3" json:"Gid,omitempty"`
	Uid string `protobuf:"bytes,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
}

func (x *DeleteUserGroupMapIn) Reset() {
	*x = DeleteUserGroupMapIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserGroupMapIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserGroupMapIn) ProtoMessage() {}

func (x *DeleteUserGroupMapIn) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserGroupMapIn.ProtoReflect.Descriptor instead.
func (*DeleteUserGroupMapIn) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteUserGroupMapIn) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *DeleteUserGroupMapIn) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type DeleteUserGroupMapOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteUserGroupMapOut) Reset() {
	*x = DeleteUserGroupMapOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserGroupMapOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserGroupMapOut) ProtoMessage() {}

func (x *DeleteUserGroupMapOut) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserGroupMapOut.ProtoReflect.Descriptor instead.
func (*DeleteUserGroupMapOut) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{16}
}

type DeleteGroupIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid string `protobuf:"bytes,1,opt,name=Gid,proto3" json:"Gid,omitempty"`
}

func (x *DeleteGroupIn) Reset() {
	*x = DeleteGroupIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGroupIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupIn) ProtoMessage() {}

func (x *DeleteGroupIn) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupIn.ProtoReflect.Descriptor instead.
func (*DeleteGroupIn) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteGroupIn) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

type DeleteGroupOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteGroupOut) Reset() {
	*x = DeleteGroupOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteGroupOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupOut) ProtoMessage() {}

func (x *DeleteGroupOut) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupOut.ProtoReflect.Descriptor instead.
func (*DeleteGroupOut) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{18}
}

type GetContactListIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameOrObjectId string `protobuf:"bytes,1,opt,name=NameOrObjectId,proto3" json:"NameOrObjectId,omitempty"`
	Page           int64  `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	Size           int64  `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
}

func (x *GetContactListIn) Reset() {
	*x = GetContactListIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetContactListIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactListIn) ProtoMessage() {}

func (x *GetContactListIn) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactListIn.ProtoReflect.Descriptor instead.
func (*GetContactListIn) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{19}
}

func (x *GetContactListIn) GetNameOrObjectId() string {
	if x != nil {
		return x.NameOrObjectId
	}
	return ""
}

func (x *GetContactListIn) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetContactListIn) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetContactListOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContactList []*Contact `protobuf:"bytes,1,rep,name=ContactList,proto3" json:"ContactList,omitempty"`
	Total       int64      `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *GetContactListOut) Reset() {
	*x = GetContactListOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetContactListOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactListOut) ProtoMessage() {}

func (x *GetContactListOut) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactListOut.ProtoReflect.Descriptor instead.
func (*GetContactListOut) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{20}
}

func (x *GetContactListOut) GetContactList() []*Contact {
	if x != nil {
		return x.ContactList
	}
	return nil
}

func (x *GetContactListOut) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteContactIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectId string `protobuf:"bytes,1,opt,name=ObjectId,proto3" json:"ObjectId,omitempty"`
}

func (x *DeleteContactIn) Reset() {
	*x = DeleteContactIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteContactIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContactIn) ProtoMessage() {}

func (x *DeleteContactIn) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContactIn.ProtoReflect.Descriptor instead.
func (*DeleteContactIn) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteContactIn) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type DeleteContactOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteContactOut) Reset() {
	*x = DeleteContactOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteContactOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContactOut) ProtoMessage() {}

func (x *DeleteContactOut) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContactOut.ProtoReflect.Descriptor instead.
func (*DeleteContactOut) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{22}
}

type GetContactApplicationListIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int64 `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Size int64 `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
}

func (x *GetContactApplicationListIn) Reset() {
	*x = GetContactApplicationListIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetContactApplicationListIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactApplicationListIn) ProtoMessage() {}

func (x *GetContactApplicationListIn) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactApplicationListIn.ProtoReflect.Descriptor instead.
func (*GetContactApplicationListIn) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{23}
}

func (x *GetContactApplicationListIn) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetContactApplicationListIn) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetContactApplicationListOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicationList []*Application `protobuf:"bytes,1,rep,name=ApplicationList,proto3" json:"ApplicationList,omitempty"`
	Total           int64          `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *GetContactApplicationListOut) Reset() {
	*x = GetContactApplicationListOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetContactApplicationListOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactApplicationListOut) ProtoMessage() {}

func (x *GetContactApplicationListOut) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactApplicationListOut.ProtoReflect.Descriptor instead.
func (*GetContactApplicationListOut) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{24}
}

func (x *GetContactApplicationListOut) GetApplicationList() []*Application {
	if x != nil {
		return x.ApplicationList
	}
	return nil
}

func (x *GetContactApplicationListOut) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetGroupContactApplicationListIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid  string `protobuf:"bytes,1,opt,name=Gid,proto3" json:"Gid,omitempty"`
	Page int64  `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	Size int64  `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
}

func (x *GetGroupContactApplicationListIn) Reset() {
	*x = GetGroupContactApplicationListIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupContactApplicationListIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupContactApplicationListIn) ProtoMessage() {}

func (x *GetGroupContactApplicationListIn) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupContactApplicationListIn.ProtoReflect.Descriptor instead.
func (*GetGroupContactApplicationListIn) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{25}
}

func (x *GetGroupContactApplicationListIn) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *GetGroupContactApplicationListIn) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGroupContactApplicationListIn) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetGroupContactApplicationListOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicationList []*Application `protobuf:"bytes,1,rep,name=ApplicationList,proto3" json:"ApplicationList,omitempty"`
	Total           int64          `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
}

func (x *GetGroupContactApplicationListOut) Reset() {
	*x = GetGroupContactApplicationListOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupContactApplicationListOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupContactApplicationListOut) ProtoMessage() {}

func (x *GetGroupContactApplicationListOut) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupContactApplicationListOut.ProtoReflect.Descriptor instead.
func (*GetGroupContactApplicationListOut) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{26}
}

func (x *GetGroupContactApplicationListOut) GetApplicationList() []*Application {
	if x != nil {
		return x.ApplicationList
	}
	return nil
}

func (x *GetGroupContactApplicationListOut) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateContactApplicationIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjectId    string `protobuf:"bytes,1,opt,name=ObjectId,proto3" json:"ObjectId,omitempty"`
	ContactType int64  `protobuf:"varint,2,opt,name=ContactType,proto3" json:"ContactType,omitempty"`
	Notice      string `protobuf:"bytes,3,opt,name=Notice,proto3" json:"Notice,omitempty"`
}

func (x *CreateContactApplicationIn) Reset() {
	*x = CreateContactApplicationIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateContactApplicationIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContactApplicationIn) ProtoMessage() {}

func (x *CreateContactApplicationIn) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContactApplicationIn.ProtoReflect.Descriptor instead.
func (*CreateContactApplicationIn) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{27}
}

func (x *CreateContactApplicationIn) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *CreateContactApplicationIn) GetContactType() int64 {
	if x != nil {
		return x.ContactType
	}
	return 0
}

func (x *CreateContactApplicationIn) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

type CreateContactApplicationOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicationId string `protobuf:"bytes,1,opt,name=ApplicationId,proto3" json:"ApplicationId,omitempty"`
}

func (x *CreateContactApplicationOut) Reset() {
	*x = CreateContactApplicationOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateContactApplicationOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContactApplicationOut) ProtoMessage() {}

func (x *CreateContactApplicationOut) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContactApplicationOut.ProtoReflect.Descriptor instead.
func (*CreateContactApplicationOut) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{28}
}

func (x *CreateContactApplicationOut) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

type UpdateContactApplicationIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApplicationId string `protobuf:"bytes,1,opt,name=ApplicationId,proto3" json:"ApplicationId,omitempty"`
	Status        int64  `protobuf:"varint,2,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *UpdateContactApplicationIn) Reset() {
	*x = UpdateContactApplicationIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateContactApplicationIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContactApplicationIn) ProtoMessage() {}

func (x *UpdateContactApplicationIn) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContactApplicationIn.ProtoReflect.Descriptor instead.
func (*UpdateContactApplicationIn) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateContactApplicationIn) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *UpdateContactApplicationIn) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateContactApplicationOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateContactApplicationOut) Reset() {
	*x = UpdateContactApplicationOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_user_rpc_user_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateContactApplicationOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContactApplicationOut) ProtoMessage() {}

func (x *UpdateContactApplicationOut) ProtoReflect() protoreflect.Message {
	mi := &file_apps_user_rpc_user_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContactApplicationOut.ProtoReflect.Descriptor instead.
func (*UpdateContactApplicationOut) Descriptor() ([]byte, []int) {
	return file_apps_user_rpc_user_proto_rawDescGZIP(), []int{30}
}

var File_apps_user_rpc_user_proto protoreflect.FileDescriptor

var file_apps_user_rpc_user_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x5c,
	0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x6f, 0x62, 0x69,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0xb1, 0x01, 0x0a,
	0x0b, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x20,
	0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69,
	0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65,
	0x22, 0xe5, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x6f, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x26,
	0x0a, 0x0e, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x4c, 0x61, 0x73, 0x74, 0x4d, 0x73,
	0x67, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4c, 0x61, 0x73,
	0x74, 0x4d, 0x73, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x49, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x74, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x4f, 0x75, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x45,
	0x78, 0x70, 0x69, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x66,
	0x72, 0x65, 0x73, 0x68, 0x41, 0x66, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0c, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x41, 0x66, 0x74, 0x65, 0x72, 0x22, 0x54, 0x0a,
	0x0a, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x25, 0x0a, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4f,
	0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x22, 0x45, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69, 0x7a,
	0x65, 0x22, 0x48, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x75, 0x74, 0x12,
	0x24, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x36, 0x0a, 0x08, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x22, 0x0b, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x75, 0x74,
	0x22, 0x53, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e,
	0x6f, 0x74, 0x69, 0x63, 0x65, 0x22, 0x22, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x4f, 0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x47, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x47, 0x69, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x0d, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x47,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x47, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x74,
	0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x63,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x55, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x55, 0x69, 0x64, 0x22, 0x10, 0x0a,
	0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4f, 0x75, 0x74, 0x22,
	0x3a, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x47, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x47, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x69, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x61,
	0x70, 0x4f, 0x75, 0x74, 0x22, 0x21, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x47, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x47, 0x69, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4f, 0x75, 0x74, 0x22, 0x62, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x12, 0x26, 0x0a,
	0x0e, 0x4e, 0x61, 0x6d, 0x65, 0x4f, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x4e, 0x61, 0x6d, 0x65, 0x4f, 0x72, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x58, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x75, 0x74, 0x12, 0x2d, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x52, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x2d, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4f, 0x75, 0x74, 0x22, 0x45, 0x0a, 0x1b, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69, 0x7a,
	0x65, 0x22, 0x6f, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x41,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x75,
	0x74, 0x12, 0x39, 0x0a, 0x0f, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x22, 0x5c, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x47, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x47, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65,
	0x22, 0x74, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69,
	0x73, 0x74, 0x4f, 0x75, 0x74, 0x12, 0x39, 0x0a, 0x0f, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x62, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x0f, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x72, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x22, 0x43, 0x0a, 0x1b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22,
	0x5a, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x12, 0x24, 0x0a,
	0x0d, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1d, 0x0a, 0x1b, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x32, 0xa1, 0x07, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x0b, 0x2e, 0x70,
	0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x4f, 0x75, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x12, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x49, 0x6e, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x4f, 0x75, 0x74, 0x12, 0x2c, 0x0a, 0x0b, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x49, 0x6e, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x75, 0x74, 0x12, 0x29, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x1a, 0x0d,
	0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x12, 0x34, 0x0a,
	0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x11, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x1a,
	0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4f, 0x75, 0x74, 0x12, 0x34, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x6e, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4f, 0x75, 0x74, 0x12, 0x49, 0x0a, 0x12, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x61, 0x70, 0x12,
	0x18, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x61,
	0x70, 0x4f, 0x75, 0x74, 0x12, 0x34, 0x0a, 0x0b, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4f, 0x75, 0x74, 0x12, 0x3d, 0x0a, 0x0e, 0x67, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x49, 0x6e, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x75, 0x74, 0x12, 0x3a, 0x0a, 0x0d, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x49, 0x6e, 0x1a,
	0x14, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x4f, 0x75, 0x74, 0x12, 0x5e, 0x0a, 0x19, 0x67, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73,
	0x74, 0x49, 0x6e, 0x1a, 0x20, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69,
	0x73, 0x74, 0x4f, 0x75, 0x74, 0x12, 0x6d, 0x0a, 0x1e, 0x67, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x1a, 0x25, 0x2e,
	0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73,
	0x74, 0x4f, 0x75, 0x74, 0x12, 0x5b, 0x0a, 0x18, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e,
	0x1a, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x75,
	0x74, 0x12, 0x5b, 0x0a, 0x18, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x2e,
	0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x1a, 0x1f, 0x2e,
	0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_user_rpc_user_proto_rawDescOnce sync.Once
	file_apps_user_rpc_user_proto_rawDescData = file_apps_user_rpc_user_proto_rawDesc
)

func file_apps_user_rpc_user_proto_rawDescGZIP() []byte {
	file_apps_user_rpc_user_proto_rawDescOnce.Do(func() {
		file_apps_user_rpc_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_user_rpc_user_proto_rawDescData)
	})
	return file_apps_user_rpc_user_proto_rawDescData
}

var file_apps_user_rpc_user_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_apps_user_rpc_user_proto_goTypes = []interface{}{
	(*User)(nil),                              // 0: pb.User
	(*Application)(nil),                       // 1: pb.Application
	(*Contact)(nil),                           // 2: pb.Contact
	(*LoginIn)(nil),                           // 3: pb.LoginIn
	(*LoginOut)(nil),                          // 4: pb.LoginOut
	(*RegisterIn)(nil),                        // 5: pb.RegisterIn
	(*RegisterOut)(nil),                       // 6: pb.RegisterOut
	(*GetListIn)(nil),                         // 7: pb.GetListIn
	(*GetListOut)(nil),                        // 8: pb.GetListOut
	(*UpdateIn)(nil),                          // 9: pb.UpdateIn
	(*UpdateOut)(nil),                         // 10: pb.UpdateOut
	(*CreateGroupIn)(nil),                     // 11: pb.CreateGroupIn
	(*CreateGroupOut)(nil),                    // 12: pb.CreateGroupOut
	(*UpdateGroupIn)(nil),                     // 13: pb.UpdateGroupIn
	(*UpdateGroupOut)(nil),                    // 14: pb.UpdateGroupOut
	(*DeleteUserGroupMapIn)(nil),              // 15: pb.DeleteUserGroupMapIn
	(*DeleteUserGroupMapOut)(nil),             // 16: pb.DeleteUserGroupMapOut
	(*DeleteGroupIn)(nil),                     // 17: pb.DeleteGroupIn
	(*DeleteGroupOut)(nil),                    // 18: pb.DeleteGroupOut
	(*GetContactListIn)(nil),                  // 19: pb.GetContactListIn
	(*GetContactListOut)(nil),                 // 20: pb.GetContactListOut
	(*DeleteContactIn)(nil),                   // 21: pb.DeleteContactIn
	(*DeleteContactOut)(nil),                  // 22: pb.DeleteContactOut
	(*GetContactApplicationListIn)(nil),       // 23: pb.GetContactApplicationListIn
	(*GetContactApplicationListOut)(nil),      // 24: pb.GetContactApplicationListOut
	(*GetGroupContactApplicationListIn)(nil),  // 25: pb.GetGroupContactApplicationListIn
	(*GetGroupContactApplicationListOut)(nil), // 26: pb.GetGroupContactApplicationListOut
	(*CreateContactApplicationIn)(nil),        // 27: pb.CreateContactApplicationIn
	(*CreateContactApplicationOut)(nil),       // 28: pb.CreateContactApplicationOut
	(*UpdateContactApplicationIn)(nil),        // 29: pb.UpdateContactApplicationIn
	(*UpdateContactApplicationOut)(nil),       // 30: pb.UpdateContactApplicationOut
}
var file_apps_user_rpc_user_proto_depIdxs = []int32{
	0,  // 0: pb.GetListOut.UserList:type_name -> pb.User
	2,  // 1: pb.GetContactListOut.ContactList:type_name -> pb.Contact
	1,  // 2: pb.GetContactApplicationListOut.ApplicationList:type_name -> pb.Application
	1,  // 3: pb.GetGroupContactApplicationListOut.ApplicationList:type_name -> pb.Application
	3,  // 4: pb.user.login:input_type -> pb.LoginIn
	5,  // 5: pb.user.register:input_type -> pb.RegisterIn
	7,  // 6: pb.user.getUserList:input_type -> pb.GetListIn
	9,  // 7: pb.user.updateUser:input_type -> pb.UpdateIn
	11, // 8: pb.user.createGroup:input_type -> pb.CreateGroupIn
	13, // 9: pb.user.updateGroup:input_type -> pb.UpdateGroupIn
	15, // 10: pb.user.deleteUserGroupMap:input_type -> pb.DeleteUserGroupMapIn
	17, // 11: pb.user.deleteGroup:input_type -> pb.DeleteGroupIn
	19, // 12: pb.user.getContactList:input_type -> pb.GetContactListIn
	21, // 13: pb.user.deleteContact:input_type -> pb.DeleteContactIn
	23, // 14: pb.user.getContactApplicationList:input_type -> pb.GetContactApplicationListIn
	25, // 15: pb.user.getGroupContactApplicationList:input_type -> pb.GetGroupContactApplicationListIn
	27, // 16: pb.user.createContactApplication:input_type -> pb.CreateContactApplicationIn
	29, // 17: pb.user.updateContactApplication:input_type -> pb.UpdateContactApplicationIn
	4,  // 18: pb.user.login:output_type -> pb.LoginOut
	6,  // 19: pb.user.register:output_type -> pb.RegisterOut
	8,  // 20: pb.user.getUserList:output_type -> pb.GetListOut
	10, // 21: pb.user.updateUser:output_type -> pb.UpdateOut
	12, // 22: pb.user.createGroup:output_type -> pb.CreateGroupOut
	14, // 23: pb.user.updateGroup:output_type -> pb.UpdateGroupOut
	16, // 24: pb.user.deleteUserGroupMap:output_type -> pb.DeleteUserGroupMapOut
	18, // 25: pb.user.deleteGroup:output_type -> pb.DeleteGroupOut
	20, // 26: pb.user.getContactList:output_type -> pb.GetContactListOut
	22, // 27: pb.user.deleteContact:output_type -> pb.DeleteContactOut
	24, // 28: pb.user.getContactApplicationList:output_type -> pb.GetContactApplicationListOut
	26, // 29: pb.user.getGroupContactApplicationList:output_type -> pb.GetGroupContactApplicationListOut
	28, // 30: pb.user.createContactApplication:output_type -> pb.CreateContactApplicationOut
	30, // 31: pb.user.updateContactApplication:output_type -> pb.UpdateContactApplicationOut
	18, // [18:32] is the sub-list for method output_type
	4,  // [4:18] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_apps_user_rpc_user_proto_init() }
func file_apps_user_rpc_user_proto_init() {
	if File_apps_user_rpc_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apps_user_rpc_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Application); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Contact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGroupIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGroupOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGroupIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateGroupOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserGroupMapIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserGroupMapOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGroupIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteGroupOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetContactListIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetContactListOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteContactIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteContactOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetContactApplicationListIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetContactApplicationListOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupContactApplicationListIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupContactApplicationListOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateContactApplicationIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateContactApplicationOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateContactApplicationIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_user_rpc_user_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateContactApplicationOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_user_rpc_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_user_rpc_user_proto_goTypes,
		DependencyIndexes: file_apps_user_rpc_user_proto_depIdxs,
		MessageInfos:      file_apps_user_rpc_user_proto_msgTypes,
	}.Build()
	File_apps_user_rpc_user_proto = out.File
	file_apps_user_rpc_user_proto_rawDesc = nil
	file_apps_user_rpc_user_proto_goTypes = nil
	file_apps_user_rpc_user_proto_depIdxs = nil
}
