// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.3
// source: common/pb/message.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageForm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransportType int32  `protobuf:"varint,1,opt,name=transportType,proto3" json:"transportType,omitempty"`
	From          string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	ToType        int32  `protobuf:"varint,4,opt,name=toType,proto3" json:"toType,omitempty"`
	Content       string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ContentType   int32  `protobuf:"varint,6,opt,name=contentType,proto3" json:"contentType,omitempty"`
	FileSuffix    string `protobuf:"bytes,7,opt,name=fileSuffix,proto3" json:"fileSuffix,omitempty"`
	File          []byte `protobuf:"bytes,8,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *MessageForm) Reset() {
	*x = MessageForm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageForm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageForm) ProtoMessage() {}

func (x *MessageForm) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageForm.ProtoReflect.Descriptor instead.
func (*MessageForm) Descriptor() ([]byte, []int) {
	return file_common_pb_message_proto_rawDescGZIP(), []int{0}
}

func (x *MessageForm) GetTransportType() int32 {
	if x != nil {
		return x.TransportType
	}
	return 0
}

func (x *MessageForm) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MessageForm) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *MessageForm) GetToType() int32 {
	if x != nil {
		return x.ToType
	}
	return 0
}

func (x *MessageForm) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageForm) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *MessageForm) GetFileSuffix() string {
	if x != nil {
		return x.FileSuffix
	}
	return ""
}

func (x *MessageForm) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

var File_common_pb_message_proto protoreflect.FileDescriptor

var file_common_pb_message_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xdf, 0x01,
	0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x12, 0x24, 0x0a,
	0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x66,
	0x69, 0x6c, 0x65, 0x53, 0x75, 0x66, 0x66, 0x69, 0x78, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x75, 0x66, 0x66, 0x69, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x66,
	0x69, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x42,
	0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_pb_message_proto_rawDescOnce sync.Once
	file_common_pb_message_proto_rawDescData = file_common_pb_message_proto_rawDesc
)

func file_common_pb_message_proto_rawDescGZIP() []byte {
	file_common_pb_message_proto_rawDescOnce.Do(func() {
		file_common_pb_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_pb_message_proto_rawDescData)
	})
	return file_common_pb_message_proto_rawDescData
}

var file_common_pb_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_pb_message_proto_goTypes = []interface{}{
	(*MessageForm)(nil), // 0: pb.MessageForm
}
var file_common_pb_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_pb_message_proto_init() }
func file_common_pb_message_proto_init() {
	if File_common_pb_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_pb_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageForm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_pb_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_pb_message_proto_goTypes,
		DependencyIndexes: file_common_pb_message_proto_depIdxs,
		MessageInfos:      file_common_pb_message_proto_msgTypes,
	}.Build()
	File_common_pb_message_proto = out.File
	file_common_pb_message_proto_rawDesc = nil
	file_common_pb_message_proto_goTypes = nil
	file_common_pb_message_proto_depIdxs = nil
}
