// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	message "jt-chat/apps/message/api/internal/handler/message"
	ws "jt-chat/apps/message/api/internal/handler/ws"
	"jt-chat/apps/message/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/get_next_msg_list",
				Handler: message.GetNextMsgListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/get_previous_msg_list",
				Handler: message.GetPreviousMsgListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/msg"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/connect",
				Handler: ws.WsConnectHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1/ws"),
	)
}
