// Code generated by goctl. DO NOT EDIT.
package types

type DownloadFileReq struct {
	MsgId    string `json:"msg_id"`
	FilePath string `json:"file_path"`
}

type DownloadFileResp struct {
	Name string `json:"name"`
	Ext  string `json:"ext"`
	Size int64  `json:"size"`
	Data []byte `json:"data"`
}

type GetNextMsgListReq struct {
	MsgId    string `json:"msg_id"`
	TargetId string `json:"target_id"`
	Size     int64  `json:"size"`
}

type GetNextMsgListResp struct {
	MessageList []Message `json:"message_list"`
}

type GetPreviousMsgListReq struct {
	MsgId    string `json:"msg_id"`
	TargetId string `json:"target_id"`
	Size     int64  `json:"size"`
}

type GetPreviousMsgListResp struct {
	MessageList []Message `json:"message_list"`
}

type Message struct {
	MsgId         string `json:"msg_id"`
	TransportType int64  `json:"transport_type"`
	From          string `json:"from"`
	To            string `json:"to"`
	ToType        int64  `json:"to_type"`
	Content       string `json:"content"`
	ContentType   int64  `json:"content_type"`
	FileSuffix    string `json:"file_suffix"`
	FilePath      string `json:"file_path"`
	CreateAt      string `json:"create_at"`
}
