// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	fileFieldNames          = builder.RawFieldNames(&File{})
	fileRows                = strings.Join(fileFieldNames, ",")
	fileRowsExpectAutoSet   = strings.Join(stringx.Remove(fileFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	fileRowsWithPlaceHolder = strings.Join(stringx.Remove(fileFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	fileModel interface {
		Insert(ctx context.Context, data *File) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*File, error)
		Update(ctx context.Context, data *File) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFileModel struct {
		conn  sqlx.SqlConn
		table string
	}

	File struct {
		Id        int64        `db:"id"`
		FileId    string       `db:"file_id"`    // 文件ID
		Hash      string       `db:"hash"`       // HASH值
		Uid       string       `db:"uid"`        // 上传人
		Name      string       `db:"name"`       // 文件名
		Ext       string       `db:"ext"`        // 文件类型
		Size      int64        `db:"size"`       // 大小
		Path      string       `db:"path"`       // 本地路径
		DeletedAt sql.NullTime `db:"deleted_at"` // 删除时间
		CreatedAt time.Time    `db:"created_at"` // 创建时间
		UpdatedAt time.Time    `db:"updated_at"` // 更新时间
	}
)

func newFileModel(conn sqlx.SqlConn) *defaultFileModel {
	return &defaultFileModel{
		conn:  conn,
		table: "`file`",
	}
}

func (m *defaultFileModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultFileModel) FindOne(ctx context.Context, id int64) (*File, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", fileRows, m.table)
	var resp File
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFileModel) Insert(ctx context.Context, data *File) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, fileRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.FileId, data.Hash, data.Uid, data.Name, data.Ext, data.Size, data.Path, data.DeletedAt)
	return ret, err
}

func (m *defaultFileModel) Update(ctx context.Context, data *File) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, fileRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.FileId, data.Hash, data.Uid, data.Name, data.Ext, data.Size, data.Path, data.DeletedAt, data.Id)
	return err
}

func (m *defaultFileModel) tableName() string {
	return m.table
}
