// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userContactFieldNames          = builder.RawFieldNames(&UserContact{})
	userContactRows                = strings.Join(userContactFieldNames, ",")
	userContactRowsExpectAutoSet   = strings.Join(stringx.Remove(userContactFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userContactRowsWithPlaceHolder = strings.Join(stringx.Remove(userContactFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userContactModel interface {
		Insert(ctx context.Context, data *UserContact) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserContact, error)
		FindOneByContactId(ctx context.Context, contactId string) (*UserContact, error)
		Update(ctx context.Context, data *UserContact) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserContactModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserContact struct {
		Id             int64          `db:"id"`
		ContactId      string         `db:"contact_id"`       // contact_id
		Uid            string         `db:"uid"`              // uid
		ObjectId       string         `db:"object_id"`        // gid或uid
		ContactType    int64          `db:"contact_type"`     // 联系人类型
		NoteName       string         `db:"note_name"`        // 备注名称
		LastMsgId      sql.NullInt64  `db:"last_msg_id"`      // 最后一条消息ID
		LastMsgContent sql.NullString `db:"last_msg_content"` // 最后一条消息内容
		LastMsgTime    sql.NullTime   `db:"last_msg_time"`    // 最后一条消息时间
		DeletedAt      sql.NullTime   `db:"deleted_at"`       // 删除时间
		CreatedAt      time.Time      `db:"created_at"`       // 创建时间
		UpdatedAt      time.Time      `db:"updated_at"`       // 更新时间
	}
)

func newUserContactModel(conn sqlx.SqlConn) *defaultUserContactModel {
	return &defaultUserContactModel{
		conn:  conn,
		table: "`user_contact`",
	}
}

func (m *defaultUserContactModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserContactModel) FindOne(ctx context.Context, id int64) (*UserContact, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userContactRows, m.table)
	var resp UserContact
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserContactModel) FindOneByContactId(ctx context.Context, contactId string) (*UserContact, error) {
	var resp UserContact
	query := fmt.Sprintf("select %s from %s where `contact_id` = ? limit 1", userContactRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, contactId)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserContactModel) Insert(ctx context.Context, data *UserContact) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userContactRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.ContactId, data.Uid, data.ObjectId, data.ContactType, data.NoteName, data.LastMsgId, data.LastMsgContent, data.LastMsgTime, data.DeletedAt)
	return ret, err
}

func (m *defaultUserContactModel) Update(ctx context.Context, newData *UserContact) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userContactRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ContactId, newData.Uid, newData.ObjectId, newData.ContactType, newData.NoteName, newData.LastMsgId, newData.LastMsgContent, newData.LastMsgTime, newData.DeletedAt, newData.Id)
	return err
}

func (m *defaultUserContactModel) tableName() string {
	return m.table
}
